export const usersData = [
    {
        id: 1,
        first_name: 'Hieu',
        last_name: 'Nguyen',
        email: 'nguyenhieu@ou.edu.vn',
        username: 'hieungn',
        img: 'https://res.cloudinary.com/ddphodfop/image/upload/v1641881634/cpur3y5uupzjs8zectti.jpg',
        role: {
            id: 1,
            name: 'Quản trị viên',
        },
        major: { id: 2, name: 'Kế toán' },
        status: 1,
    },
    {
        id: 2,
        first_name: 'Linh',
        last_name: 'Bui',
        email: 'builinh@ou.edu.vn',
        username: 'builn',
        img: 'https://res.cloudinary.com/ddphodfop/image/upload/v1651589513/jzdvhrhanbh0gkqnafeh.png',
        role: {
            id: 2,
            name: 'Giáo vụ',
        },
        major: { id: 1, name: 'CNTT' },
        status: 0,
    },
    {
        id: 3,
        first_name: 'Nam',
        last_name: 'Lưn',
        email: 'namnlun@ou.edu.vn',
        username: 'namln',
        img: 'https://res.cloudinary.com/ddphodfop/image/upload/v1641876860/wczdjilmgyb3czsyiix1.png',
        role: { id: 3, name: 'Giảng viên' },
        major: { id: 3, name: 'QTKD' },
        status: 1,
    },
];
